apiVersion:  v1
kind: Service
metadata:
  name: flask-app
  namespace: frontend
  labels:
    app: flask-app
spec:
  selector:
    app: flask-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30000
  
  



