name: Build image

on:
  workflow_dispatch


jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

    publish-image:
      needs: build
      runs-on: ubuntu-latest
      permissions:
        packages: write
        contents: read
      steps:
            - name: Checkout repository
              uses: actions/checkout@v2
            
            - name: Login to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{ github.repository_owner }}
                password: ${{secrets.GITHUB_TOKEN}}

            - name: Build and push
              uses: docker/build-push-action@v6
              with:
                platforms: linux/amd64,linux/arm64
                push: true
                tags: ghcr.io/${{ github.repository_owner }}/practicum-web:latest

            # - name: Login to DockerHub
            #   run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
            
            # - name: Build and push
            #   run: |
            #     docker buildx build --platform linux/amd64,linux/arm64 -t ${{ secrets.DOCKERHUB_USERNAME }}/practicum-web:latest --push .